[project]
name = "pywatchpower"
version = "1.0.0"
license = "GPL-3.0"
description = ""
authors = [{ name = "Dmitry Berezovsky" }]
maintainers = [{ name = "Dmitry Berezovsky" }]
keywords = [
    "inverter", "solar", "power", "watchpower", "msx", "mks",
    "axioma", "axpert", "mppsolar", "voltronic", "voltacon", "effecta"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
]
requires-python = ">=3.12,<4.0"
readme = "README.md"

[project.urls]
repository = "https://github.com/cchangelabs/py-watch-power"

[project.scripts]
py-watch-power = "py_watch_power:cli.entrypoint"

[tool.poetry]
packages = [{ include = "py_watch_power", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
hid = "~=1.0.6"
cli-rack = "~=1.2.0"

# Optional dependencies
paho-mqtt = { version = "^2.1", optional = true }

[tool.poetry.group.dev.dependencies]
# Dev tools
ruff = ">=0.13.0"
licenseheaders = ">=0.8"
mypy = ">=1.18.1"
pre-commit = "~=3.8"
commitizen = ">=4.9,<5.0"

[tool.poetry.extras]
hass-mqtt = ["paho-mqtt"]

[tool.commitizen]
version_provider = "pep621"
bump_version = "bump: version $current_version → $new_version"
update_changelog_on_bump = true
pre_bump_hooks = []
version_files = [
    "src/py_watch_power/__version__.py",
]

[tool.black]
line-length = 120
target-version = ['py311']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''


[tool.mypy]
python_version = "3.12"
show_error_codes = true
ignore_errors = false
warn_return_any = false
disallow_any_generics = false
pretty = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/stubs"
exclude = ["test_.*\\.py$", ]

[[tool.mypy.overrides]]
# External libs which doesn't have type hints (py.typed marker)
module = ["hid.*", "cli_rack.*"]
ignore_missing_imports = true
follow_imports = "skip"

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [".*pyi"]

[tool.ruff.lint.isort]
known-third-party = ["openepd", "ccl_common", "ilcdlib", "cqd_datamodel", "ccl_api_common"]
force-sort-within-sections = true

[tool.ruff.lint.per-file-ignores]
"**.pyi" = ["UP"]
"test_*.py" = ["D103", "D104", "D100", "D101", "D102", "D106"]
"__version__.py" = ["D104", "D100", "D101", "D102"]
"**/settings/*.py" = ["F405"]

[tool.ruff.lint]
extend-ignore = [
    "S101", # Use of assert statement. We have a lot of asserts for mypy type checking.
    "S324", # We cannot ignore sha1 hash in codebase because it is used by box.com

    "D202",
    # W504 line break after binary operator
    ##### DOCSTRINGS #####
    # Missing docstring in public module
    "D100",
    # Missing docstring in __init__
    "D107",
    # Missing docstring in magic method
    "D105",
    # Missing docstring in public package
    "D104",
    # Missing docstring in public nested class
    "D106",
    # One black line required before class docstring
    "D203",
    #`no-blank-line-before-class
    "D211",
    # Multi-line docstring summary should start at the second line
    "D212",
    # Multi-line docstring summary should start at the first line
    "D213",
    # Raw string in exception
    "EM101",
    # f-string in exception
    "EM102",
]
extend-select = ["S", "E", "B", "A", "EM", "UP"]

[tool.ruff.lint.flake8-type-checking]
# Add quotes around type annotations, if doing so would allow
# an import to be moved into a type-checking block.
quote-annotations = true
